site_name: Rail Network Resilience â€” Japan & Switzerland
theme:
  name: material
nav:
  - Home: index.md
  - Analysis:
    - Comparison: analysis/Comparison_Analysis.ipynb
    - Japan: analysis/Japan_Analysis.ipynb
    - Switzerland: analysis/Switzerland_Analysis.ipynb
  - Preprocessing:
    - Japan: preprocessing/Japan_Construction_Story.ipynb
    - Switzerland: preprocessing/Switzerland_Construction_Story.ipynb
plugins:
  - mkdocs-jupyter:
      include_source: true
      allow_errors: false
      ignore_h1_titles: true