site_name: My Docs
theme:
  name: material
nav:
  - Home: index.md
  - Preprocessing:
    - Japan: preprocessing/Japan_Construction_Story.ipynb
    - Switzerland: preprocessing/Switzerland_Construction_Story.ipynb
plugins:
  - mkdocs-jupyter:
      include_source: true
      execute: true
      allow_errors: false
      ignore_h1_titles: true